/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from '@latticexyz/recs';

export function defineContractComponents(world: World) {
  return {
    Game: (() => {
      const name = 'Game';
      return defineComponent(
        world,
        {
          id: RecsType.Number,
          name: RecsType.String,
          seed: RecsType.Number, // felt252
          over: RecsType.Boolean,
          tower_count: RecsType.Number,
          mob_count: RecsType.Number,
          mob_remaining: RecsType.Number,
          mob_alive: RecsType.Number,
          wave: RecsType.Number,
          gold: RecsType.Number,
          health: RecsType.Number,
          tick: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Mob: (() => {
      const name = 'Mob';
      return defineComponent(
        world,
        {
          id: RecsType.Number,
          index: RecsType.Number,
          category: RecsType.Number,
          health: RecsType.Number,
          speed: RecsType.Number,
          defence: RecsType.Number,
          reward: RecsType.Number,
          tick: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Tower: (() => {
      const name = 'Tower';
      return defineComponent(
        world,
        {
          id: RecsType.Number,
          index: RecsType.Number,
          category: RecsType.Number,
          cooldown: RecsType.Number,
          attack: RecsType.Number,
          range: RecsType.Number,
          level: RecsType.Number,
          cost: RecsType.Number,
          hit: RecsType.Number,
          tick: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Tile: (() => {
      const name = 'Tile';
      return defineComponent(
        world,
        {
          army: RecsType.Number,
          owner: RecsType.Number,
          dispatched: RecsType.Number,
          to: RecsType.Number,
          from: RecsType.Number,
          order: RecsType.Number, // felt252
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthStatus: (() => {
      const name = 'AuthStatus';
      return defineComponent(
        world,
        {
          is_authorized: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthRole: (() => {
      const name = 'AuthRole';
      return defineComponent(
        world,
        {
          id: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
